<a href="https://colab.research.google.com/github/DharaniMohanachandran22/Machine_learning-/blob/main/Gradient_Desent_Calculus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
xdata=np.array([-40,-10,0,8,15,22],dtype=float)
ydata=np.array([-40,14,32,46,56,72],dtype=float)

In [ ]:
x=22
m=1.8
c=32

In [ ]:
y=m*x +c
y

71.6

In [ ]:
xdata*m+c

array([-40. ,  14. ,  32. ,  46.4,  59. ,  71.6])

In [ ]:
m=1
c=1
y_pred=xdata*m+c
y_pred

array([-39.,  -9.,   1.,   9.,  16.,  23.])

In [ ]:
ydata

array([-40.,  14.,  32.,  46.,  56.,  72.])

In [ ]:
#ERROR CALCULATION
print(y_pred-ydata)#residual/error
print((y_pred - ydata)**2) # if u sum the error as it is the +ve and -ve vals will get cancel out each other
print(np.sum((y_pred -ydata)**2)/len(ydata))
#np.sum(...): This part sums up all the squared differences calculated in the previous step.
print(np.mean((y_pred -ydata)**2))
#np.mean() function calculates the average of the values in the input array.

[  1. -23. -31. -37. -40. -49.]
[1.000e+00 5.290e+02 9.610e+02 1.369e+03 1.600e+03 2.401e+03]
1143.5
1143.5


In [ ]:
def error(y,y_hat):
  return np.mean((y-y_hat)**2)

In [ ]:
error(y_pred,ydata)

1143.5

RANDOM search value of c

In [ ]:
m=1.8
c_vals=[25,26,27,28,29,30,31,32,33,34]

for cc in c_vals:
  y_pred=xdata*m + cc
  print(cc, error(ydata,y_pred))
  #which is have very lowest error ,it is suitable value for c_vals

25 43.55333333333335
26 31.553333333333345
27 21.553333333333345
28 13.553333333333342
29 7.553333333333341
30 3.5533333333333386
31 1.5533333333333363
32 1.5533333333333337
33 3.553333333333331
34 7.553333333333328


In [ ]:
m=1
c=50
y_pred=xdata*m +c
print(error(ydata,y_pred))
print(error(y_pred,ydata))

620.8333333333334
620.8333333333334


In [ ]:
x = np.array([-40, -10, 0, 8, 15, 22], dtype=float)
y = np.array([-40, 14, 32, 46, 59, 72], dtype=float)

In [ ]:
m=1
c=1
lr=0.001
y_hat=m*x + c
n = len(x)
print(y_hat)
e=error(ydata,y_hat)
print(m,c,e)
# these are partial derivatives of the error with respest to m and c using the gradient of the mean squard error loss function.
de_dm=(-2/n)*np.sum(x*(y-y_hat))
de_dc=(-2/n)*np.sum(y-y_hat)
print(de_dm,de_dc)
#update the m,c =>to reduce error
m=m-(lr*de_dm)
c=c-(lr*de_dc)
print(m,c)
y_hat=m*x+c
e=error(y,y_hat)
print(m,c,e)

[-39.  -9.   1.   9.  16.  23.]
1 1 1143.5
-609.6666666666666 -60.666666666666664
1.6096666666666666 1.0606666666666666
1.6096666666666666 1.0606666666666666 962.7677954999998


In [ ]:
m=-1000
c=-1000
lr=0.001
epochs=1000
n=len(x)
for i in range(epochs):
  y_hat=x*m+c;
  e=error(y,y_hat);
  if (i%50==0):
    print(m,c,e)
  de_dm=(-2/n)*np.sum(x*(y-y_hat))
  de_dc=(-2/n)*np.sum(y-y_hat)
  m=m-(lr*de_dm)
  c=c-(lr*de_dc)

-1000 -1000 412995600.1666667
-0.09414046303916644 -903.6900260666728 874044.2917934192
0.08620811345969655 -814.7056729015914 715705.8543052323
0.2494055303252847 -734.1837366605912 586051.3891176303
0.3970828637905104 -661.3194410245796 479884.61995055835
0.5307160746480097 -595.384543947071 392950.6076196656
0.6516407597371462 -535.7200592406132 321765.2210882673
0.7610655005637296 -481.72967034075 263475.50087683887
0.860083942465312 -432.8737704213964 215745.31849132932
0.9496857250471392 -388.664069295574 176661.74934241918
1.0307663731330905 -348.6587132001826 144658.40678068224
1.1041362470865919 -312.457868689513 118452.66463820853
1.170528641955542 -279.6997265007311 96994.25228915304
1.230607116388086 -250.05688545197714 79423.1620281457
1.2849721245681116 -223.233080231954 65035.18178346271
1.3341670174532945 -198.96022037691046 53253.671789129585
1.378683473295084 -176.99571084107544 43606.45408476387
1.4189664117159313 -157.12002738099295 35706.888623274346
1.455418440457

TensorFlow Gradients

In [ ]:
import tensorflow  as tf

In [ ]:
x=tf.Variable(3.0)
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [ ]:
y=x**2
print(y)

tf.Tensor(9.0, shape=(), dtype=float32)


In [ ]:
#Manually calculation for derivation
dy_dx=2*x
print(dy_dx)

tf.Tensor(6.0, shape=(), dtype=float32)


In [ ]:
with tf.GradientTape() as tape:
  y=x**2
dy_dx= tape.gradient(y,x)
dy_dx.numpy()
#print(dy_dx) => #tf.Tensor(6.0, shape=(), dtype=float32)

6.0

In [ ]:
with tf.GradientTape() as tape:
  y=tf.math.sin(x**2)
dy_dx= tape.gradient(y,x)
dy_dx.numpy()

-5.4667816

Using tensorFlow Gradients

In [ ]:
import tensorflow as tf

In [ ]:
x = np.array([-40, -10, 0, 8, 15, 22], dtype=float)
y = np.array([-40, 14, 32, 46, 59, 72], dtype=float)

In [ ]:
def error(y_hat):
  return tf.reduce_mean((y-y_hat)**2)

In [ ]:
m=tf.Variable(1.0)
c=tf.Variable(0.0)

In [ ]:
lr=0.001
epoch=2000

In [ ]:
for i in range(1000):
  with tf.GradientTape() as tape:
    y_hat=m*x + c
    mse=error(y_hat)
    if(i%100==0):
      print("m=%.2f c=%.2f mse=%.2f"%(m,c,mse))
    [de_dm,de_dc]=tape.gradient(mse,[m,c])
    m.assign_sub(de_dm*lr)
    c.assign_sub(de_dc*lr)

m=1.00 c=0.00 mse=1246.67
m=1.75 c=5.80 mse=685.64
m=1.76 c=10.54 mse=459.74
m=1.77 c=14.43 mse=308.27
m=1.77 c=17.61 mse=206.72
m=1.78 c=20.22 mse=138.62
m=1.78 c=22.35 mse=92.96
m=1.79 c=24.10 mse=62.35
m=1.79 c=25.53 mse=41.82
m=1.79 c=26.71 mse=28.06
