In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

**bold text**

In [ ]:
b=np.array([[1,2,3],[2,3,4]])
print(b.shape)
print(type(b))

(2, 3)
<class 'numpy.ndarray'>


In [ ]:
a.dtype

dtype('int64')

to check np.array() |  n=>number of rank in type of numpy

In [ ]:
np.random.random(3)

array([0.48052618, 0.21489601, 0.61103199])

random.random (we can give range)

In [ ]:
np.ones((3,2))
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.random.random((3,2))

array([[0.03465593, 0.50240458],
       [0.24619371, 0.84311353],
       [0.27558392, 0.95077962]])

In [ ]:
np.ones((2,3,5,6,4))

array([[[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
        

In [ ]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
f=np.arange(10,50,5)
print(f)
w=np.arange(10,50,8)
print(w)

[10 15 20 25 30 35 40 45]
[10 18 26 34 42]


In [ ]:
f=np.linspace(0.,1.,3)
print(f)
y=np.linspace(0.,1.,5)
print(y)

[0.  0.5 1. ]
[0.   0.25 0.5  0.75 1.  ]


arange=>incremant
linspace=> split

we can identity function
random int

In [ ]:
z=np.array(([1,2,3,4,5],[2,3,4,7,8]))
print(z[1,3])
print(z[1:3])
print(z[0:2,0])

7
[[2 3 4 7 8]]
[1 2]


1=>inmlicite/3=> explicite(3->2) /0=>columns/ (0:2)-> 1,2

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[1:3,2:3]
print(b)

[[ 7]
 [11]]


In [ ]:
r=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]])
row1=r[1,:]
print(row1)
row1.shape
row2=r[1:2,:]
print(row2)
row2.shape
row3=r[[1],:]
print(row3)
row3.shape

[3 4 5 6]
[[3 4 5 6]]
[[3 4 5 6]]


(1, 4)

In [ ]:
r

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [ ]:
r=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]])
col1=r[:,1]
col2=r[:,1:2]
print(col1)
print(col2)


[2 4 6]
[[2]
 [4]
 [6]]


(4,)=>column blank=> that means all columns
1)output-> onliy list
(