<a href="https://colab.research.google.com/github/DharaniMohanachandran22/Machine_learning-/blob/main/numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5],[6,7,8,9],[3,4,5,6]])
print(a.shape)
b=np.array([0,2,0,1])
print(a[np.arange(4),b])

(4, 4)
[1 4 6 4]


In [ ]:
a=np.array([1,8,9,-3,2,4,7,9])
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))
print(np.argsort(a)[::-1])
print(np.where(a>5)[0])
print(np.where(a>=a[np.argmax(a)])[0])

2
3
[3 0 4 5 6 1 2 7]
[7 2 1 6 5 4 0 3]
[1 2 6 7]
[2 7]


In [ ]:
a=[0]
a=np.append(a,[1,2,3,4])
print(a)

[0 1 2 3 4]


In [ ]:
r=[9,8,7,6,5]
d=np.delete(r,[1,3])
print(d)

[9 7 5]


print(v.dot(w))
print(np.dot(v,w))
print(v @ w)  => dot prodect

In [ ]:
x=np.array([[1,2],[3,4],[5,6]])


min,max,transpose,sum

In [ ]:
w=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(w.shape)
print(w)
z=w.squeeze()
print(z)
t=z.reshape(-100,3)#t=z.reshape(-100,4)=> error
print(t)

(3, 3)
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


board casting

In [ ]:
a=np.array([1,2,3])
b=np.array([[4],[5],[6]])
c=a+b
print(c)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


boolean,cheesheet

In [ ]:
a=np.array([[1,8,9,-3,2,4,7,9],[3,4,5,6,7,8,1,2],[2,3,4,5,6,7,8,9]])
print(np.where(a>5)[1])
print(np.where(a>5)[0])
print(np.where(a>5))

[1 2 6 7 3 4 5 4 5 6 7]
[0 0 0 0 1 1 1 2 2 2 2]
(array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2]), array([1, 2, 6, 7, 3, 4, 5, 4, 5, 6, 7]))
